In [1]:
import pickle
from sage.all import sigma, nth_prime, pari
import ast
import math

from scipy.signal import find_peaks, correlate
from scipy.fft import fft, fftfreq
import numpy as np


def tau(n):
    def step1(n, k):
        return 35*k^4 - 52*k^3*n + 18*k^2*n^2
    def step2(n, k):
        return sigma(k) * sigma(n - k)
    def step3(n):
        ans = 0
        for k in range(1, n):
            ans=ans+step1(n, k) * step2(n, k)
        return 24*ans
    return n^4 * sigma(n) - step3(n)

def tau_prime(k):
            pn=nth_prime(k)
            return tau(pn)

    
def P_matrix(lst):
    lenlist=len(lst)
    columns=[lst]
    for k in range(1,lenlist):
        column=[0]*(k-1)
        column=column+[-k]
        column=flatten(column+[lst])
        column=column+[lst]
        column=column[:lenlist]
        columns+=[column]
    return (matrix(columns)).transpose()



from sage.all import *
precision_bits = 100
x = polygen(QQ)  # Can remain in preamble if all polynomials are in one variable


main_dets=[]
main_j_list=[]
dets=[]  

tau_prime_list = [(k, tau_prime(k)) for k in range(1, 400)]
h_list = [(0, 1)] + tau_prime_list   


j_list=[(0,0)]# <<< this is the deforming code
for k in range(1,53):
    sm=0
    for r in [1..k-1]:
        sm=sm+j_list[r][1]*h_list[k-r][1] 
    j_k=k*h_list[k][1]-sm
    j_list.append((k,j_k))
    main_j_list.append((-1,j_list))
print("undeformed j_list:")
print(j_list)
    
for n in range(2,5):
    print("undeformed",n)
    sliced=j_list[1:n+1] ### undeformed
    inputs=[pair[1] for pair in sliced]
    pl=P_matrix(inputs)
    show(pl)
    det=pl.det()
    dets.append((-1,n,det))
    print((-1,n,det))
    main_dets.append((-1,dets))

undeformed j_list:
[(0, 0), (1, -24), (2, -72), (3, 18810), (4, 518528), (5, 10323516), (6, 34401720), (7, -3989135538), (8, -155766935712), (9, -2992865260284), (10, -17819053859692), (11, 1003061903788624), (12, 42629200194219392), (13, 887368323086397882), (14, 6892985740168908252), (15, -240526862448815484060), (16, -11647363698649213927200), (17, -259657289589751889306000), (18, -2462054998035044872641948), (19, 55685703329232047991048336), (20, 3154243898799515612423138408), (21, 75338156120567569892139003822), (22, 833389948436624377972027401376), (23, -12198334508698806157459655177412), (24, -846700942602570744349975288586400), (25, -21678764514315662032598172517166934), (26, -272086694067516700774544929205162192), (27, 2437537980730937013116397249312332520), (28, 225086801337991985559395131107073147008), (29, 6189508197797528062404657187839688754254), (30, 86502818088520663990377403879139460701180), (31, -402849623279827776392944185677661083969704), (32, -591944643273640657287

[-24  -1]
[-72 -24]

(-1, 2, 504)
undeformed 3


[  -24    -1     0]
[  -72   -24    -2]
[18810   -72   -24]

(-1, 3, 28980)
undeformed 4


[   -24     -1      0      0]
[   -72    -24     -2      0]
[ 18810    -72    -24     -3]
[518528  18810    -72    -24]

(-1, 4, -401856)


In [18]:
from sage.all import (QQ, sigma, nth_prime, matrix, flatten, polygen)
import pickle

Rc.<c> = QQ[]
Rn.<n> = QQ[]
Rd.<d>=QQ[]
Rkk.<kk>=QQ[]

def tau(n):
    def step1(n, k):
        return 35*k^4 - 52*k^3*n + 18*k^2*n^2

    def step2(n, k):
        return sigma(k) * sigma(n - k)

    def step3(n):
        ans = 0
        for k in range(1, n):
            ans += step1(n, k) * step2(n, k)
        return 24*ans

    return n^4 * sigma(n) - step3(n)


def tau_prime(k):
    return tau(nth_prime(k))

def P_matrix(lst):
    L = len(lst)
    columns = [lst]
    for k in range(1, L):
        column = [0]*(k-1) + [-k]
        column = flatten(column + [lst])
        column = column + [lst]
        column = column[:L]
        columns.append(column)
    return matrix(columns).transpose()


            
tau_prime_list=[(k,tau_prime(k)) for k in range(1,300)]
h_list=[[0,1]]+tau_prime_list  
c_polys=[]
c_cffs=[]

for n in range(2,201):
    print("n:",n)
    data=[]
    
    for c in range (1,n+5):
        j_list=[(0,c)]
        
        for k in range(1,n+1):
            sm=0
            
            for r in range(1,k):
                sm+=j_list[r][1]*h_list[k-r][1] 
    
            j_k=k*h_list[k][1]-sm
            j_list.append((k,j_k))
    
        sliced = j_list[:n]
        inputs = [pair[1] for pair in sliced]
        det = P_matrix(inputs).det()
        data.append((c, det))
        
    c_poly = Rc.lagrange_polynomial(data)
    
    lp=list(c_poly)
    lp.reverse()
    c_polys.append((n, lp))
    
    

with open('/Users/barrybrent/data2/run21jan26no1.txt', 'wb') as wfile:
    pickle.dump(c_polys, wfile) # ouput snipped

n: 2
n: 3
n: 4
n: 5
n: 6
n: 7
n: 8
n: 9
n: 10
n: 11
n: 12
n: 13
n: 14
n: 15
n: 16
n: 17
n: 18
n: 19
n: 20
n: 21
n: 22
n: 23
n: 24
n: 25
n: 26
n: 27
n: 28
n: 29
n: 30
n: 31
n: 32
n: 33
n: 34
n: 35
n: 36
n: 37
n: 38
n: 39
n: 40
n: 41
n: 42
n: 43
n: 44
n: 45
n: 46
n: 47
n: 48
n: 49
n: 50
n: 51
n: 52
n: 53
n: 54
n: 55
n: 56
n: 57
n: 58
n: 59
n: 60
n: 61
n: 62
n: 63
n: 64
n: 65
n: 66
n: 67
n: 68
n: 69
n: 70
n: 71
n: 72
n: 73
n: 74
n: 75
n: 76
n: 77
n: 78
n: 79
n: 80
n: 81
n: 82
n: 83
n: 84
n: 85
n: 86
n: 87
n: 88
n: 89
n: 90
n: 91
n: 92
n: 93
n: 94
n: 95
n: 96
n: 97
n: 98
n: 99
n: 100
n: 101
n: 102
n: 103
n: 104
n: 105
n: 106
n: 107
n: 108
n: 109
n: 110
n: 111
n: 112
n: 113
n: 114
n: 115
n: 116
n: 117
n: 118
n: 119
n: 120
n: 121
n: 122
n: 123
n: 124
n: 125
n: 126
n: 127
n: 128
n: 129
n: 130
n: 131
n: 132
n: 133
n: 134
n: 135
n: 136
n: 137
n: 138
n: 139
n: 140
n: 141
n: 142
n: 143
n: 144
n: 145
n: 146
n: 147
n: 148
n: 149
n: 150
n: 151
n: 152
n: 153
n: 154
n: 155
n: 156
n: 157
n: 158
n: 159


KeyboardInterrupt: 

In [8]:
import pickle
with open('/Users/barrybrent/data2/run21jan26no1.txt', 'rb') as rfile:
    c_polys = pickle.load(rfile)

Rc.<c> = QQ[]
for tupl in c_polys[:20]:
    print((tupl[0],Rc(tupl[1])))

(2, -24*c^2 + 1)
(3, -144*c^3 - 72*c^2 + 1)
(4, 114588*c^4 - 576*c^3 - 144*c^2 + 1)
(5, 12479232*c^5 + 572940*c^4 - 1440*c^3 - 240*c^2 + 1)
(6, 1198192320*c^6 + 74875392*c^5 + 1718820*c^4 - 2880*c^3 - 360*c^2 + 1)
(7, 17919600192*c^7 + 8387346240*c^6 + 262063872*c^5 + 4010580*c^4 - 5040*c^3 - 504*c^2 + 1)
(8, -20578729954608*c^8 + 143356801536*c^7 + 33549384960*c^6 + 698836992*c^5 + 8021160*c^4 - 8064*c^3 - 672*c^2 + 1)
(9, -6136737862569984*c^9 - 185208569591472*c^8 + 645105606912*c^7 + 100648154880*c^6 + 1572383232*c^5 + 14438088*c^4 - 12096*c^3 - 864*c^2 + 1)
(10, -1015814349610805376*c^10 - 61367378625699840*c^9 - 926042847957360*c^8 + 2150352023040*c^7 + 251620387200*c^6 + 3144766464*c^5 + 24063480*c^4 - 17280*c^3 - 1080*c^2 + 1)
(11, -48059370493945125120*c^11 - 11173957845718859136*c^10 - 337520582441349120*c^9 - 3395490442510320*c^8 + 5913468063360*c^7 + 553564851840*c^6 + 5765405184*c^5 + 37814040*c^4 - 23760*c^3 - 1320*c^2 + 1)
(12, 41697300444381866268864*c^12 - 576712445927