In [1]:
# most of this cell's code was run in notebook 'primeTau1oct25no2'
from sage.all import sigma, nth_prime
from sage.arith.all import moebius
import pickle
import ast

def nieburTau(n):
    def step1(n, k):
        return 35*k^4 - 52*k^3*n + 18*k^2*n^2
    def step2(n, k):
        return sigma(k) * sigma(n - k)
    def step3(n):
        ans = 0
        for k in range(1, n):
            ans += step1(n, k) * step2(n, k)
        return 24*ans
    return n^4 * sigma(n) - step3(n)


def primeTau(n):
    return nieburTau(nth_prime(n))


primeTau_list =[] 
for k in range(1, 501):
    primeTau_list.append([k,primeTau(k)])
    if k%100==0:
        print(k)

with open('/Users/barrybrent/data/run17oct25no15.txt', 'wb') as wfile:
    pickle.dump(primeTau_list, wfile) #output snipped

with open('/Users/barrybrent/data/run17oct25no15.txt', 'rb') as rfile:
    primeTau_list = pickle.load(rfile)
h_list=[[0,1]]+primeTau_list 
j_list=[(0,0)] 
for n in [1..500]:# so j(1) = 1 = h(0) as required.
    sm=0
    for r in [1..n-1]: 
        sm=sm+j_list[r][1]*h_list[n-r][1] 
    j_n=n*h_list[n][1]-sm
    j_list.append((n,j_n))

print(h_list[:10])
print()
print(j_list[:10])
    
with open('/Users/barrybrent/data/run17oct25no16.txt', 'wb') as wfile:
    pickle.dump(j_list, wfile) # ouput snipped
# That (0,0) shouldn't be there.

100
200
300
400
500
[[0, 1], [1, -24], [2, 252], [3, 4830], [4, -16744], [5, 534612], [6, -577738], [7, -6905934], [8, 10661420], [9, 18643272]]

[(0, 0), (1, -24), (2, -72), (3, 18810), (4, 518528), (5, 10323516), (6, 34401720), (7, -3989135538), (8, -155766935712), (9, -2992865260284)]


In [4]:
primeTau(1)

-24

In [12]:
def P_matrix(lst):
    lenlist = len(lst)
    columns = [lst]
    for k in range(1, lenlist):
        column = [0]*(k-1) + [-k] + lst
        column = column[:lenlist]
        columns.append(column)
    return matrix(columns).transpose()

# Increase PARI stack size to handle large polynomial root computations
pari.allocatemem(7*10^9)  # Allocate 7GB for PARI stack


import pickle
from sage.all import sigma, nth_prime, pari
import ast
import math
import time

from scipy.signal import find_peaks, correlate
from scipy.fft import fft, fftfreq
import numpy as np


def tau(n):
    def step1(n, k):
        return 35*k^4 - 52*k^3*n + 18*k^2*n^2
    def step2(n, k):
        return sigma(k) * sigma(n - k)
    def step3(n):
        ans = 0
        for k in range(1, n):
            ans=ans+step1(n, k) * step2(n, k)
        return 24*ans
    return n^4 * sigma(n) - step3(n)

def tau_prime(k):
            pn=nth_prime(k)
            return tau(pn)




    

from sage.all import sigma, nth_prime
from sage.arith.all import moebius
import pickle
import ast

def nieburTau(n):
    def step1(n, k):
        return 35*k^4 - 52*k^3*n + 18*k^2*n^2
    def step2(n, k):
        return sigma(k) * sigma(n - k)
    def step3(n):
        ans = 0
        for k in range(1, n):
            ans += step1(n, k) * step2(n, k)
        return 24*ans
    return n^4 * sigma(n) - step3(n)


def primeTau(n):
    return nieburTau(nth_prime(n))



with open('/Users/barrybrent/data/run17oct25no16.txt', 'rb') as rfile:
    j_list = pickle.load(rfile)


from sage.all import *
precision_bits = 100
CIF = ComplexIntervalField(precision_bits)
x = polygen(QQ)  # Can remain in preamble if all polynomials are in one variable
matrix_list=[]
charpol_list=[]
roots_list=[]
aar_list=[]
centers_list=[]
max_diameter_list=[]
mins_list=[]
maxes_list=[]
log_mins_list=[]
log_maxes_list=[]
no=[]
tests=[]
for n in range(1,10):
    lst = [j[1] for j in j_list[1:n+1]] # cuts out the dummy offset
    inpt=[j for j in lst]
    pl=P_matrix(inpt)
    test=pl.det()/(primeTau(n)*factorial(n))
    tests.append(test)
    print((n,test))

    
print("tests:")
print(tests)

(1, 1)
(2, 1)
(3, 1)
(4, 1)
(5, 1)
(6, 1)
(7, 1)
(8, 1)
(9, 1)
tests:
[1, 1, 1, 1, 1, 1, 1, 1, 1]


In [13]:
import pickle
from sage.all import sigma, nth_prime
import ast

def nieburTau(n):
    def step1(n, k):
        return 35*k^4 - 52*k^3*n + 18*k^2*n^2
    def step2(n, k):
        return sigma(k) * sigma(n - k)
    def step3(n):
        ans = 0
        for k in range(1, n):
            ans += step1(n, k) * step2(n, k)
        return 24*ans
    return n^4 * sigma(n) - step3(n)

def h(n):
    if n>0:
        return nieburTau(nth_prime(n)) # i.e., tauPrime(n)
    if n==0:
        return 1
        
with open('/Users/barrybrent/data/run17oct25no16.txt', 'rb') as rfile:
    j_list = pickle.load(rfile) #tauPrime(n) j-companion

def P_matrix(lst):
    lenlist=len(lst)
    columns=[lst]
    for k in range(1,lenlist):
        column=[0]*(k-1)
        column=column+[-k]
        column=flatten(column+[lst])
        column=column+[lst]
        column=column[:lenlist]
        columns+=[column]
    return (matrix(columns)).transpose()

from sage.all import *
precision_bits = 100
CIF = ComplexIntervalField(precision_bits)
x = polygen(QQ)  # Can remain in preamble if all polynomials are in one variable
matrix_list=[]
charpol_list=[]
roots_list=[]
aar_list=[]
centers_list=[]
max_diameter_list=[]
mins_list=[]
log_mins_list=[]
maxes_list=[]
log_maxes_list=[]
dets=[]
tests=[]
for n in range(1,4):
    print("------------------------------------------------------------------")
    print("n:",n,"undeformed:")
    undeformed_j_list=j_list[1:n+1]
    undeformed_inputs=[pair[1] for pair in undeformed_j_list]
    print("undeformed inputs:")
    print(undeformed_inputs)
    print()
    pl_undeformed=P_matrix(undeformed_inputs)
    undeformed_det=pl_undeformed.det()
    print("matrix:")
    show(pl_undeformed)
    print()
    print("h(n):",h(n),"det/n!:",undeformed_det/factorial(n))

------------------------------------------------------------------
n: 1 undeformed:
undeformed inputs:
[-24]

matrix:


[-24]


h(n): -24 det/n!: -24
------------------------------------------------------------------
n: 2 undeformed:
undeformed inputs:
[-24, -72]

matrix:


[-24  -1]
[-72 -24]


h(n): 252 det/n!: 252
------------------------------------------------------------------
n: 3 undeformed:
undeformed inputs:
[-24, -72, 18810]

matrix:


[  -24    -1     0]
[  -72   -24    -2]
[18810   -72   -24]


h(n): 4830 det/n!: 4830


In [7]:
import pickle
from sage.all import sigma, nth_prime
import ast
import time

# Increase PARI stack size to handle large polynomial root computations
pari.allocatemem(7*10^9)  # Allocate 7GB for PARI stack

def nieburTau(n):
    def step1(n, k):
        return 35*k^4 - 52*k^3*n + 18*k^2*n^2
    def step2(n, k):
        return sigma(k) * sigma(n - k)
    def step3(n):
        ans = 0
        for k in range(1, n):
            ans += step1(n, k) * step2(n, k)
        return 24*ans
    return n^4 * sigma(n) - step3(n)

def h(n):
    if n>0:
        return nieburTau(nth_prime(n)) # i.e., tauPrime(n)
    if n==0:
        return 1

h_list=[h(n) for n in range(0,302)]
with open('/Users/barrybrent/data/run17oct25no16.txt', 'rb') as rfile:
    j_list = pickle.load(rfile) #tauPrime(n) j-companion
    
def P_matrix(lst):
    lenlist=len(lst)
    columns=[lst]
    for k in range(1,lenlist):
        column=[0]*(k-1)
        column=column+[-k]
        column=flatten(column+[lst])
        column=column+[lst]
        column=column[:lenlist]
        columns+=[column]
    return (matrix(columns)).transpose()

from sage.all import *
precision_bits = 100
CC = ComplexField(precision_bits)
x = polygen(QQ)  # Can remain in preamble if all polynomials are in one variable
matrix_list=[]
charpol_list=[]
dets_list=[]
tests=[]
for n in range(1, 101):
    undeformed_j_list=j_list[1:n+1]
    inputs=[pair[1] for pair in undeformed_j_list]
    pl=P_matrix(inputs) ### UNDEFORMED
    det=pl.det()
    test=det-h_list[n]*factorial(n)
    tests.append(test)
    dets_list.append((n,det))
    matrix_list.append((n,pl))
    cp=pl.charpoly()
    charpol_list.append((n,cp))
print("tests:")
print(tests)
with open('/Users/barrybrent/data/run8nov25no1.txt', 'wb') as wfile:
    pickle.dump(matrix_list, wfile) #output snipped
with open('/Users/barrybrent/data/run8nov25no2.txt', 'wb') as wfile:
    pickle.dump(charpol_list, wfile) #output snipped
with open('/Users/barrybrent/data/run8nov25no3.txt', 'wb') as wfile:
    pickle.dump(dets_list, wfile) #output snipped

PARI stack size set to 7000000000 bytes, maximum size set to 7000002560
tests:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [20]:
def submatrix_delete_rows_cols(M, rows_to_delete):
    n = M.nrows()
    delete_set = set(rows_to_delete)
    indices = [i for i in range(n) if (i+1) not in delete_set]
    return M.matrix_from_rows_and_columns(indices, indices)

def display_submatrices_by_deletion_set(M, m):
    from sage.combinat.combination import Combinations
    n = M.nrows()
    print(f"Submatrices obtained by deleting {m} rows and columns:")
    for deletion_set in Combinations(range(1, n+1), m):
        print("deletion set:")
        print(deletion_set)
        submat = submatrix_delete_rows_cols(M, deletion_set)
        show(submat)
        print("determinant:",submat.det())
    print()

with open('/Users/barrybrent/data/run8nov25no1.txt', 'rb') as rfile:
    matrix_list = pickle.load(rfile) 
with open('/Users/barrybrent/data/run8nov25no2.txt', 'rb') as rfile:
    charpol_list = pickle.load(rfile) 
with open('/Users/barrybrent/data/run8nov25no3.txt', 'rb') as rfile:
    dets_list = pickle.load(rfile) 

no=[]
for k in range(0,100):
    nc=charpol_list[k][0]
    nm=matrix_list[k][0]
    if nc!=nm:
        no.append(k)
print("no:",len(no))
for k in range(1,3):
    print("==========================================================================================================")
    matrix_pair= matrix_list[k]
    print("n:",matrix_pair[0])
    M=matrix_pair[1]
    poly_pair=charpol_list[k]
    print("Original matrix M:")
    show(M)
    print("chi:")
    print(poly_pair[1])
    print("__________________________________________________________________________________________________________")
    display_submatrices_by_deletion_set(M, 1)
    print("__________________________________________________________________________________________________________")
    display_submatrices_by_deletion_set(M, 2)
    print("__________________________________________________________________________________________________________")
    display_submatrices_by_deletion_set(M, 3)

no: 0
n: 2
Original matrix M:


[-24  -1]
[-72 -24]

chi:
x^2 + 48*x + 504
__________________________________________________________________________________________________________
Submatrices obtained by deleting 1 rows and columns:
deletion set:
[1]


[-24]

determinant: -24
deletion set:
[2]


[-24]

determinant: -24

__________________________________________________________________________________________________________
Submatrices obtained by deleting 2 rows and columns:
deletion set:
[1, 2]


[]

determinant: 1

__________________________________________________________________________________________________________
Submatrices obtained by deleting 3 rows and columns:

n: 3
Original matrix M:


[  -24    -1     0]
[  -72   -24    -2]
[18810   -72   -24]

chi:
x^3 + 72*x^2 + 1512*x - 28980
__________________________________________________________________________________________________________
Submatrices obtained by deleting 1 rows and columns:
deletion set:
[1]


[-24  -2]
[-72 -24]

determinant: 432
deletion set:
[2]


[  -24     0]
[18810   -24]

determinant: 576
deletion set:
[3]


[-24  -1]
[-72 -24]

determinant: 504

__________________________________________________________________________________________________________
Submatrices obtained by deleting 2 rows and columns:
deletion set:
[1, 2]


[-24]

determinant: -24
deletion set:
[1, 3]


[-24]

determinant: -24
deletion set:
[2, 3]


[-24]

determinant: -24

__________________________________________________________________________________________________________
Submatrices obtained by deleting 3 rows and columns:
deletion set:
[1, 2, 3]


[]

determinant: 1



In [22]:
n=5
m=2
cmb=Combinations(range(1, n+1), m)
for tupl in cmb:
    print(tupl)

[1, 2]
[1, 3]
[1, 4]
[1, 5]
[2, 3]
[2, 4]
[2, 5]
[3, 4]
[3, 5]
[4, 5]


In [35]:
import pickle
from sage.all import sigma, nth_prime
import ast

def tau(n):
    def step1(n, k):
        return 35*k^4 - 52*k^3*n + 18*k^2*n^2
    def step2(n, k):
        return sigma(k) * sigma(n - k)
    def step3(n):
        ans = 0
        for k in range(1, n):
            ans += step1(n, k) * step2(n, k)
        return 24*ans
    return n^4 * sigma(n) - step3(n)

def h(n):
    if n>0:
        return nieburTau(nth_prime(n)) # i.e., tauPrime(n)
    if n==0:
        return 1

def submatrix_delete_rows_cols(M, rows_to_delete):
    n = M.nrows()
    delete_set = set(rows_to_delete)
    indices = [i for i in range(n) if (i+1) not in delete_set]
    return M.matrix_from_rows_and_columns(indices, indices)

def checksum_submatrices_by_deletion_set(M, k):
    from sage.combinat.combination import Combinations
    n = M.nrows()
    print(f"Submatrices obtained by deleting {k} rows and columns:")
    summ=0
    combinations=Combinations(range(1, n+1), k)
    number_of_combinations=len(combinations)
    for deletion_set in combinations:
        print("deletion set:")
        print(deletion_set)
        submat = submatrix_delete_rows_cols(M, deletion_set)
        show(submat)
        sd=submat.det()
        summ+=sd*(-1)**(n-k)
        print("subdeterminant:",sd)
    print()
    cpoly=M.charpoly()
    cf=cpoly[k]
    print("sum:",summ,"coefficient:",cf)

def fact(n):
    if n==0:
        return 1
    return factorial(n)
no=[]
for k in range(0,100):
    nc=charpol_list[k][0]
    nm=matrix_list[k][0]
    if nc!=nm:
        no.append(k)
print("no:",len(no))
for k in range(2,4):
    print("==========================================================================================================")
    matrix_pair= matrix_list[k]
    n=matrix_pair[0]
    print("n:",n)
    M=matrix_pair[1]
    poly_pair=charpol_list[k]
    print("Original matrix M:")
    show(M)
    print("chi:")
    print(poly_pair[1])
    test=0
    for kk in range(0,n+1):
        if kk>0:
            term=(-1)**kk*factorial(kk)*binomial(n,kk)*tau(nth_prime(kk))*x**(n-kk)
        if kk==0:
            term=(-1)**k*factorial(kk)*binomial(n,kk)*x**(n-kk)
        test+=term
    print("test equation (3):")
    print(test)
   
    for m in range(0,n+1):
        print(checksum_submatrices_by_deletion_set(M, m))
        print("__________________________________________________________________________________________________________")

no: 0
n: 3
Original matrix M:


[  -24    -1     0]
[  -72   -24    -2]
[18810   -72   -24]

chi:
x^3 + 72*x^2 + 1512*x - 28980
test equation (3):
x^3 + 72*x^2 + 1512*x - 28980
Submatrices obtained by deleting 0 rows and columns:
deletion set:
[]


[  -24    -1     0]
[  -72   -24    -2]
[18810   -72   -24]

subdeterminant: 28980

sum: -28980 coefficient: -28980
None
__________________________________________________________________________________________________________
Submatrices obtained by deleting 1 rows and columns:
deletion set:
[1]


[-24  -2]
[-72 -24]

subdeterminant: 432
deletion set:
[2]


[  -24     0]
[18810   -24]

subdeterminant: 576
deletion set:
[3]


[-24  -1]
[-72 -24]

subdeterminant: 504

sum: 1512 coefficient: 1512
None
__________________________________________________________________________________________________________
Submatrices obtained by deleting 2 rows and columns:
deletion set:
[1, 2]


[-24]

subdeterminant: -24
deletion set:
[1, 3]


[-24]

subdeterminant: -24
deletion set:
[2, 3]


[-24]

subdeterminant: -24

sum: 72 coefficient: 72
None
__________________________________________________________________________________________________________
Submatrices obtained by deleting 3 rows and columns:
deletion set:
[1, 2, 3]


[]

subdeterminant: 1

sum: 1 coefficient: 1
None
__________________________________________________________________________________________________________
n: 4
Original matrix M:


[   -24     -1      0      0]
[   -72    -24     -2      0]
[ 18810    -72    -24     -3]
[518528  18810    -72    -24]

chi:
x^4 + 96*x^3 + 3024*x^2 - 115920*x - 401856
test equation (3):
-x^4 + 96*x^3 + 3024*x^2 - 115920*x - 401856
Submatrices obtained by deleting 0 rows and columns:
deletion set:
[]


[   -24     -1      0      0]
[   -72    -24     -2      0]
[ 18810    -72    -24     -3]
[518528  18810    -72    -24]

subdeterminant: -401856

sum: -401856 coefficient: -401856
None
__________________________________________________________________________________________________________
Submatrices obtained by deleting 1 rows and columns:
deletion set:
[1]


[  -24    -2     0]
[  -72   -24    -3]
[18810   -72   -24]

subdeterminant: 107676
deletion set:
[2]


[   -24      0      0]
[ 18810    -24     -3]
[518528    -72    -24]

subdeterminant: -8640
deletion set:
[3]


[   -24     -1      0]
[   -72    -24      0]
[518528  18810    -24]

subdeterminant: -12096
deletion set:
[4]


[  -24    -1     0]
[  -72   -24    -2]
[18810   -72   -24]

subdeterminant: 28980

sum: -115920 coefficient: -115920
None
__________________________________________________________________________________________________________
Submatrices obtained by deleting 2 rows and columns:
deletion set:
[1, 2]


[-24  -3]
[-72 -24]

subdeterminant: 360
deletion set:
[1, 3]


[  -24     0]
[18810   -24]

subdeterminant: 576
deletion set:
[1, 4]


[-24  -2]
[-72 -24]

subdeterminant: 432
deletion set:
[2, 3]


[   -24      0]
[518528    -24]

subdeterminant: 576
deletion set:
[2, 4]


[  -24     0]
[18810   -24]

subdeterminant: 576
deletion set:
[3, 4]


[-24  -1]
[-72 -24]

subdeterminant: 504

sum: 3024 coefficient: 3024
None
__________________________________________________________________________________________________________
Submatrices obtained by deleting 3 rows and columns:
deletion set:
[1, 2, 3]


[-24]

subdeterminant: -24
deletion set:
[1, 2, 4]


[-24]

subdeterminant: -24
deletion set:
[1, 3, 4]


[-24]

subdeterminant: -24
deletion set:
[2, 3, 4]


[-24]

subdeterminant: -24

sum: 96 coefficient: 96
None
__________________________________________________________________________________________________________
Submatrices obtained by deleting 4 rows and columns:
deletion set:
[1, 2, 3, 4]


[]

subdeterminant: 1

sum: 1 coefficient: 1
None
__________________________________________________________________________________________________________


In [44]:
import pickle
from sage.all import sigma, nth_prime
import ast

def tau(n):
    def step1(n, k):
        return 35*k^4 - 52*k^3*n + 18*k^2*n^2
    def step2(n, k):
        return sigma(k) * sigma(n - k)
    def step3(n):
        ans = 0
        for k in range(1, n):
            ans += step1(n, k) * step2(n, k)
        return 24*ans
    return n^4 * sigma(n) - step3(n)

def h(n):
    if n>0:
        return nieburTau(nth_prime(n)) # i.e., tauPrime(n)
    if n==0:
        return 1

def submatrix_delete_rows_cols(M, rows_to_delete):
    n = M.nrows()
    delete_set = set(rows_to_delete)
    indices = [i for i in range(n) if (i+1) not in delete_set]
    return M.matrix_from_rows_and_columns(indices, indices)

def checksum_submatrices_by_deletion_set(M, k):
    from sage.combinat.combination import Combinations
    n = M.nrows()
    print(f"Submatrices obtained by deleting {k} rows and columns:")
    summ=0
    combinations=Combinations(range(1, n+1), k)
    number_of_combinations=len(combinations)
    cpoly=M.charpoly()
    cf=cpoly[k]
    for deletion_set in combinations:
        print("deletion set:")
        print(deletion_set)
        submat = submatrix_delete_rows_cols(M, deletion_set)
        show(submat)
        sd=submat.det()*(-1)**(n-k)
        summ+=sd
        print("coefficient:",cf)
        print("subdeterminant:",sd)
    print()
    print("coefficient:",cf)
    print("checksum:")
    return summ

def fact(n):
    if n==0:
        return 1
    return factorial(n)
no=[]
for k in range(0,100):
    nc=charpol_list[k][0]
    nm=matrix_list[k][0]
    if nc!=nm:
        no.append(k)
print("no:",len(no))
for k in range(2,4):
    print("==========================================================================================================")
    matrix_pair= matrix_list[k]
    n=matrix_pair[0]
    print("n:",n)
    M=matrix_pair[1]
    poly_pair=charpol_list[k]
    print("Original matrix M:")
    show(M)
    print("chi:")
    print(poly_pair[1])
    test=0
    for kk in range(0,n+1):
        if kk>0:
            term=(-1)**kk*factorial(kk)*binomial(n,kk)*tau(nth_prime(kk))*x**(n-kk)
        if kk==0:
            term=(-1)**k*factorial(kk)*binomial(n,kk)*x**(n-kk)
        test+=term
    print("test equation (3):")
    print(test)
   
    for m in range(0,n+1):
        print(checksum_submatrices_by_deletion_set(M, m))
        print("__________________________________________________________________________________________________________")

no: 0
n: 3
Original matrix M:


[  -24    -1     0]
[  -72   -24    -2]
[18810   -72   -24]

chi:
x^3 + 72*x^2 + 1512*x - 28980
test equation (3):
x^3 + 72*x^2 + 1512*x - 28980
Submatrices obtained by deleting 0 rows and columns:
deletion set:
[]


[  -24    -1     0]
[  -72   -24    -2]
[18810   -72   -24]

coefficient: -28980
subdeterminant: -28980

coefficient: -28980
checksum:
-28980
__________________________________________________________________________________________________________
Submatrices obtained by deleting 1 rows and columns:
deletion set:
[1]


[-24  -2]
[-72 -24]

coefficient: 1512
subdeterminant: 432
deletion set:
[2]


[  -24     0]
[18810   -24]

coefficient: 1512
subdeterminant: 576
deletion set:
[3]


[-24  -1]
[-72 -24]

coefficient: 1512
subdeterminant: 504

coefficient: 1512
checksum:
1512
__________________________________________________________________________________________________________
Submatrices obtained by deleting 2 rows and columns:
deletion set:
[1, 2]


[-24]

coefficient: 72
subdeterminant: 24
deletion set:
[1, 3]


[-24]

coefficient: 72
subdeterminant: 24
deletion set:
[2, 3]


[-24]

coefficient: 72
subdeterminant: 24

coefficient: 72
checksum:
72
__________________________________________________________________________________________________________
Submatrices obtained by deleting 3 rows and columns:
deletion set:
[1, 2, 3]


[]

coefficient: 1
subdeterminant: 1

coefficient: 1
checksum:
1
__________________________________________________________________________________________________________
n: 4
Original matrix M:


[   -24     -1      0      0]
[   -72    -24     -2      0]
[ 18810    -72    -24     -3]
[518528  18810    -72    -24]

chi:
x^4 + 96*x^3 + 3024*x^2 - 115920*x - 401856
test equation (3):
-x^4 + 96*x^3 + 3024*x^2 - 115920*x - 401856
Submatrices obtained by deleting 0 rows and columns:
deletion set:
[]


[   -24     -1      0      0]
[   -72    -24     -2      0]
[ 18810    -72    -24     -3]
[518528  18810    -72    -24]

coefficient: -401856
subdeterminant: -401856

coefficient: -401856
checksum:
-401856
__________________________________________________________________________________________________________
Submatrices obtained by deleting 1 rows and columns:
deletion set:
[1]


[  -24    -2     0]
[  -72   -24    -3]
[18810   -72   -24]

coefficient: -115920
subdeterminant: -107676
deletion set:
[2]


[   -24      0      0]
[ 18810    -24     -3]
[518528    -72    -24]

coefficient: -115920
subdeterminant: 8640
deletion set:
[3]


[   -24     -1      0]
[   -72    -24      0]
[518528  18810    -24]

coefficient: -115920
subdeterminant: 12096
deletion set:
[4]


[  -24    -1     0]
[  -72   -24    -2]
[18810   -72   -24]

coefficient: -115920
subdeterminant: -28980

coefficient: -115920
checksum:
-115920
__________________________________________________________________________________________________________
Submatrices obtained by deleting 2 rows and columns:
deletion set:
[1, 2]


[-24  -3]
[-72 -24]

coefficient: 3024
subdeterminant: 360
deletion set:
[1, 3]


[  -24     0]
[18810   -24]

coefficient: 3024
subdeterminant: 576
deletion set:
[1, 4]


[-24  -2]
[-72 -24]

coefficient: 3024
subdeterminant: 432
deletion set:
[2, 3]


[   -24      0]
[518528    -24]

coefficient: 3024
subdeterminant: 576
deletion set:
[2, 4]


[  -24     0]
[18810   -24]

coefficient: 3024
subdeterminant: 576
deletion set:
[3, 4]


[-24  -1]
[-72 -24]

coefficient: 3024
subdeterminant: 504

coefficient: 3024
checksum:
3024
__________________________________________________________________________________________________________
Submatrices obtained by deleting 3 rows and columns:
deletion set:
[1, 2, 3]


[-24]

coefficient: 96
subdeterminant: 24
deletion set:
[1, 2, 4]


[-24]

coefficient: 96
subdeterminant: 24
deletion set:
[1, 3, 4]


[-24]

coefficient: 96
subdeterminant: 24
deletion set:
[2, 3, 4]


[-24]

coefficient: 96
subdeterminant: 24

coefficient: 96
checksum:
96
__________________________________________________________________________________________________________
Submatrices obtained by deleting 4 rows and columns:
deletion set:
[1, 2, 3, 4]


[]

coefficient: 1
subdeterminant: 1

coefficient: 1
checksum:
1
__________________________________________________________________________________________________________
